#!/bin/bash

# Padrão da mensagem de commit
COMMIT_MSG_FILE=$1
REGEX="^(feat|fix|docs|style|refactor|test|chore): .{10,}"

echo "Verificando mensagem de commit..."

if ! grep -qE "$REGEX" "$COMMIT_MSG_FILE"; then
    echo "Mensagem de commit inválida!"
    echo "Use o formato: tipo: descrição (Exemplo: feat: adiciona autenticação com JWT)"
    exit 1
fi

echo "Mensagem de commit válida!"
