#!/bin/bash
set -e

echo "Atualizando .env após checkout..."

repo_root=$(git rev-parse --show-toplevel)
env_file="$repo_root/.env"
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "$current_branch" == "main" || "$current_branch" == "prod" ]]; then
    MODE="PRODUCTION"
else
    MODE="DEVELOPMENT"
fi

if [ -f "$env_file" ]; then
    sed -i 's/^MODE=.*/MODE='"$MODE"'/' "$env_file"
else
    echo "MODE=$MODE" > "$env_file"
fi

echo "Modo de execução atualizado no .env para $MODE."
