from .user import UserViewSet
from .aluno import AlunoViewSet
from .disciplina import DisciplinaViewSet
from .trimestre import TrimestreViewSet
from .turma import TurmaViewSet
from .curso import CursoViewSet
from .ocorrencia import OcorrenciaViewSet
from .nota import NotaViewSet
from .conselho import ConselhoViewSet
from .anotacao import AnotacaoViewSet
from .observacao import ObservacaoViewSet