# Generated by Django 5.1.3 on 2024-11-29 21:38

import core.models.user
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("uploader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conselho",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Trimestre",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.IntegerField(
                        choices=[(1, "Primeiro Trimestre"), (2, "Segundo Trimestre"), (3, "Terceiro Trimestre")],
                        unique=True,
                    ),
                ),
                ("ano", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "passage_id",
                    models.CharField(
                        default=uuid.uuid4,
                        help_text="Passage ID",
                        max_length=255,
                        unique=True,
                        verbose_name="passage_id",
                    ),
                ),
                ("email", models.EmailField(help_text="Email", max_length=255, unique=True, verbose_name="email")),
                (
                    "name",
                    models.CharField(blank=True, help_text="Username", max_length=255, null=True, verbose_name="name"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indica que este usuário está ativo.", verbose_name="Usuário está ativo"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Indica que este usuário pode acessar o Admin.",
                        verbose_name="Usuário é da equipe",
                    ),
                ),
                (
                    "matricula",
                    models.PositiveIntegerField(
                        default=None, help_text="Matrícula do aluno", null=True, unique=True, verbose_name="matricula"
                    ),
                ),
                ("reset_code", models.CharField(blank=True, max_length=6, null=True)),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
            managers=[
                ("objects", core.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("matricula", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("cpf", models.CharField(max_length=100)),
                (
                    "foto",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Anotacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "acoes",
                    models.CharField(
                        choices=[
                            ("1", "Reunião Família-Escola"),
                            ("2", "Participação em Grupo de Estudos"),
                            ("3", "Participação em SiSAE"),
                            ("4", "Reunião com Regente"),
                            ("5", "Reunião com Coordenação de Curso"),
                        ],
                        max_length=2,
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anotacoes",
                        to="core.aluno",
                    ),
                ),
                (
                    "conselho",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anotacoes",
                        to="core.conselho",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Curso",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
                (
                    "cor",
                    models.CharField(
                        default="#FFFFFF", help_text="Insira a cor em formato hexadecimal (ex: #FFFFFF)", max_length=7
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100)),
                ("carga_horaria", models.IntegerField()),
                (
                    "professor",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="disciplinas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("outro_tipo", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("1", "Atraso de Aluno"),
                            ("2", "Aluno sem Uniforme"),
                            ("3", "Reunião com Nupe"),
                            ("4", "Outro"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="core.aluno",
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="core.trimestre",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nota", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notas", to="core.aluno"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notas", to="core.disciplina"
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notas", to="core.trimestre"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conselho",
            name="trimestre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="conselho", to="core.trimestre"
            ),
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True, null=True)),
                ("ano_letivo", models.PositiveIntegerField()),
                ("numero_estudantes", models.PositiveIntegerField(default=0)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("ultima_atualizacao", models.DateTimeField(auto_now=True)),
                ("media_da_turma", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "curso",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.curso"
                    ),
                ),
                ("disciplinas", models.ManyToManyField(related_name="turmas", to="core.disciplina")),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="uploader.image",
                    ),
                ),
            ],
            options={
                "ordering": ["ano_letivo", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Observacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="core.aluno",
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="core.trimestre",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="core.turma",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="conselho",
            name="turma",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="conselho", to="core.turma"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="core.turma",
            ),
        ),
    ]
