# Generated by Django 5.1.3 on 2024-11-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_remove_turma_media_da_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="media_da_turma",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
