# Generated by Django 5.1.3 on 2024-11-29 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_trimestre_aluno_curso_disciplina_turma"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="disciplinas",
            field=models.ManyToManyField(blank=True, null=True, related_name="turmas", to="core.disciplina"),
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nota", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notas", to="core.aluno"
                    ),
                ),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notas", to="core.disciplina"
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="notas", to="core.trimestre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ocorrencia",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=100)),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "tipo",
                    models.CharField(choices=[("OC", "Ocorrência"), ("OB", "Observação")], default="OC", max_length=2),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="core.aluno",
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ocorrencias", to="core.trimestre"
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ocorrencias",
                        to="core.turma",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
    ]
