# Generated by Django 5.1.3 on 2024-11-29 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_turma_disciplinas_nota_ocorrencia"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="curso",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.curso"
            ),
        ),
    ]
