# Generated by Django 5.1.3 on 2024-11-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_turma_disciplinas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="matricula",
            field=models.PositiveIntegerField(
                default=None, help_text="Matrícula do aluno", null=True, unique=True, verbose_name="matricula"
            ),
        ),
    ]
