# Generated by Django 5.1.3 on 2024-11-29 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_user_matricula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocorrencia",
            name="trimestre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocorrencias",
                to="core.trimestre",
            ),
        ),
    ]
