# Generated by Django 5.1.3 on 2024-11-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_turma_alunos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trimestre",
            name="name",
            field=models.IntegerField(
                choices=[(1, "Primeiro Trimestre"), (2, "Segundo Trimestre"), (3, "Terceiro Trimestre")], unique=True
            ),
        ),
        migrations.AlterField(
            model_name="turma",
            name="alunos",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="turmas", to="core.aluno"
            ),
        ),
    ]
