# Generated by Django 5.1.3 on 2024-11-29 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_ocorrencia_trimestre"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conselho",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_fim", models.DateTimeField(blank=True, null=True)),
                ("ativo", models.BooleanField(default=False)),
                (
                    "trimestre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conselho", to="core.trimestre"
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="conselho", to="core.turma"
                    ),
                ),
            ],
        ),
    ]
