# Generated by Django 5.1.3 on 2024-11-29 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_conselho"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anotacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "acoes",
                    models.CharField(
                        choices=[
                            ("1", "Reunião Família-Escola"),
                            ("2", "Participação em Grupo de Estudos"),
                            ("3", "Participação em SiSAE"),
                            ("4", "Reunião com Regente"),
                            ("5", "Reunião com Coordenação de Curso"),
                        ],
                        max_length=2,
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="ocorrencia",
            name="turma",
        ),
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="core.turma",
            ),
        ),
        migrations.AddField(
            model_name="ocorrencia",
            name="outro_tipo",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="ocorrencia",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("1", "Atraso de Aluno"),
                    ("2", "Aluno sem Uniforme"),
                    ("3", "Reunião com Nupe"),
                    ("4", "Outro"),
                ],
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Observacao",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("conteudo", models.TextField()),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="core.aluno",
                    ),
                ),
                (
                    "trimestre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="core.trimestre",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observacoes",
                        to="core.turma",
                    ),
                ),
            ],
        ),
    ]
