# Generated by Django 5.1.3 on 2024-11-29 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_alter_trimestre_name_alter_turma_alunos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="turma",
            name="alunos",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="turmas",
                to="core.aluno",
            ),
        ),
    ]
