# Generated by Django 5.1.3 on 2024-11-29 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_alter_turma_alunos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="turma",
            name="alunos",
        ),
        migrations.AddField(
            model_name="aluno",
            name="turma",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to="core.turma",
            ),
        ),
    ]
