# Generated by Django 5.1.3 on 2024-11-29 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_anotacao_remove_ocorrencia_turma_aluno_turma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacao",
            name="conselho",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anotacoes",
                to="core.conselho",
            ),
        ),
    ]
