# Generated by Django 5.1.3 on 2024-11-29 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_anotacao_conselho"),
    ]

    operations = [
        migrations.AddField(
            model_name="anotacao",
            name="aluno",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="anotacoes",
                to="core.aluno",
            ),
        ),
    ]
