# Generated by Django 5.1.3 on 2024-11-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_conselho"),
        ("core", "0016_remove_turma_alunos_aluno_turma"),
    ]

    operations = []
