# Generated by Django 5.1.3 on 2024-11-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_merge_20241129_1741"),
    ]

    operations = [
        migrations.AddField(
            model_name="turma",
            name="media_da_turma",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
